jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Check if changes exist
        run: |
          git diff --exit-code || echo "Changes detected, proceeding with commit"
      
      - name: Commit changes
        run: |
          git config --global user.name "your_username"
          git config --global user.email "your_email@example.com"
          git add .
          git commit -m "Automated commit"
          git push origin master
        if: success() && github.event_name != 'push'
