name: Deploy Bot

on:
  push:
    branches:
      - master  
  workflow_dispatch:  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  

      - name: Log before deploy
        run: echo "Starting deployment process..."

      - name: Check service availability
        run: |
          python -c "
          import requests
          try:
              response = requests.get('https://your-service-url.com')
              if response.status_code == 200:
                  print('Service is available')
              else:
                  print(f'Service unavailable, status code: {response.status_code}')
          except requests.exceptions.RequestException as e:
              print(f'Service check failed: {e}')
          "

      - name: Run deploy script
        run: |
          echo "Starting deploy..."
          python main.py  # если у вас есть скрипт деплоя

      - name: Log deployment completion
        run: echo "Deployment completed."

      - name: Clean up and finish
        run: echo "Cleaning up after deployment..."
