name: Deploy on push

on:
  push:
    branches:
      - main  # или укажите другую ветку

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run deployment script
        run: |
          python deploy.py  # или ваш скрипт для деплоя
